version: "3.8"

services:
  api:
    build:
      context: ./api
    volumes:
      - ./api/src:/usr/src/api/src
      - ./api/requirements.txt:/usr/src/api/requirements.txt
    ports:
      - "3000:3000"
    depends_on:
      - cache_api
      - database_app
    env_file:
      - ./.env
    environment:
      - TARGET_ENV=asap/local # determines which secrets we'll fetch/set at runtime

  cache_api:
    image: redis:6.2.7
    ports:
      - "6379:6379"

  database_app:
    image: postgres:14.5
    environment:
      POSTGRES_DB: asap
      POSTGRES_USER: asapuser
      POSTGRES_PASSWORD: asappassword
    ports:
      - "5432:5432"

  www:
    build:
      context: ./www
    volumes:
      - ./www/src:/usr/src/www/src
      - ./www/index.html:/usr/src/www/index.html
      - ./www/jest.config.js:/usr/src/www/jest.config.js
      - ./www/package.json:/usr/src/www/package.json
      - ./www/tsconfig.json:/usr/src/www/tsconfig.json
      - ./www/tsconfig.node.json:/usr/src/www/tsconfig.node.json
      - ./www/vite.config.ts:/usr/src/www/vite.config.ts
      - ./www/yarn.lock:/usr/src/www/yarn.lock
      - /usr/src/www/node_modules
    ports:
      - "7000:7000"
      - "80:7000" # could just do 80 but I like the extra port in case there's a conflcit
    depends_on:
      - api
    command: "npm run start:local"
    env_file:
      - ./.env
    environment:
      - TARGET_ENV=asap/local # determines which secrets we'll fetch/set at runtime
