# HACK: this should be done w/ alembic outside this service, but for simplicity doing it here

async def setup_postgres_db_tables(session):
    '''Sets up the SQLite in memory db. Doing this as a function instead of using alembic for simplicity.'''

    # --- drop existing table to clear data/schema
    await session.execute('''DROP TABLE IF EXISTS "member_id";''')
    await session.execute('''DROP TABLE IF EXISTS "user";''')

    # --- create/re-create table
    await session.execute('''
        CREATE TABLE IF NOT EXISTS "user" (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            first_name TEXT,
            last_name TEXT,
            date_of_birth DATE,
            origin_country_code TEXT,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );
    ''')
    await session.execute('''
        CREATE TABLE IF NOT EXISTS "member_id" (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            value TEXT NOT NULL UNIQUE,
            user_id INTEGER NOT NULL,
            created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES "user" (id)
        );
    ''')
